/**
 * Combat-relevant archetype dedications.
 * `id` is the tag stored on combatant.archetypes[]; often matches overlay keys.
 */
export type CombatArchetypeStub = {
  id: string;
  name: string;
  matchNames: string[];
  kind: "multiclass" | "other";
  dedicationLevel: number;
  /** Existing feat-archetype-overlays.json key, if any. */
  overlayId?: string;
  /** Capabilities granted when this dedication is present. */
  grantCapabilities?: string[];
  preferPacketIds?: string[];
  scoreHints?: Record<string, number>;
  /** Soft role packet bias (does not force role). */
  roleHint?: string;
  allowMissingAon?: boolean;
  summary?: string;
};

export const COMBAT_ARCHETYPE_STUBS: CombatArchetypeStub[] = [
  // ── Multiclass dedications ────────────────────────────────
  {
    id: "champion_dedication",
    name: "Champion",
    matchNames: ["Champion"],
    kind: "multiclass",
    dedicationLevel: 2,
    overlayId: "champion_dedication",
    grantCapabilities: ["reactive_strike"],
    preferPacketIds: ["engage_and_hold"],
    scoreHints: { guardianPlant: 1.0 },
    roleHint: "champion",
  },
  {
    id: "fighter_dedication",
    name: "Fighter",
    matchNames: ["Fighter"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["reactive_strike"],
    preferPacketIds: ["engage_and_hold", "flank_crit_fish"],
    scoreHints: { martialPressure: 1.5 },
    roleHint: "fighter",
  },
  {
    id: "rogue_dedication",
    name: "Rogue",
    matchNames: ["Rogue"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["sneak_attack"],
    preferPacketIds: ["flank_sneak", "skirmish_exit"],
    scoreHints: { flankSetup: 2.0 },
    roleHint: "rogue",
  },
  {
    id: "barbarian_dedication",
    name: "Barbarian",
    matchNames: ["Barbarian"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["sudden_charge"],
    preferPacketIds: ["sudden_charge_crash"],
    scoreHints: { closeAndStrike: 2.0 },
    roleHint: "barbarian",
  },
  {
    id: "monk_dedication",
    name: "Monk",
    matchNames: ["Monk"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["flurry_of_blows"],
    preferPacketIds: ["flurry_skirmish"],
    scoreHints: { actionCompression: 1.5 },
    roleHint: "monk",
  },
  {
    id: "bard_dedication",
    name: "Bard",
    matchNames: ["Bard"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["inspire_courage"],
    preferPacketIds: ["buff_then_blast"],
    scoreHints: { mathBuffFirst: 2.0 },
    roleHint: "bard",
  },
  {
    id: "cleric_dedication",
    name: "Cleric",
    matchNames: ["Cleric"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["heal_font"],
    preferPacketIds: ["focus_fire_wounded"],
    scoreHints: { triage: 2.0 },
    roleHint: "cleric",
  },
  {
    id: "wizard_dedication",
    name: "Wizard",
    matchNames: ["Wizard"],
    kind: "multiclass",
    dedicationLevel: 2,
    grantCapabilities: ["cast_focus"],
    preferPacketIds: ["save_arbitrage_blast", "control_then_mitigate"],
    scoreHints: { focusSpell: 1.5 },
    roleHint: "wizard",
  },
  {
    id: "ranger_dedication",
    name: "Ranger",
    matchNames: ["Ranger"],
    kind: "multiclass",
    dedicationLevel: 2,
    preferPacketIds: ["kite_and_shoot"],
    scoreHints: { rangedPressure: 1.5 },
    roleHint: "ranger_archer",
  },

  // ── Other combat archetypes ───────────────────────────────
  {
    id: "archer",
    name: "Archer",
    matchNames: ["Archer"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["kite_and_shoot"],
    scoreHints: { rangedPressure: 2.5, preferCover: 1.0 },
    roleHint: "ranger_archer",
  },
  {
    id: "dual_weapon_warrior",
    name: "Dual-Weapon Warrior",
    matchNames: ["Dual-Weapon Warrior"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["engage_and_hold", "flank_crit_fish"],
    scoreHints: { actionCompression: 1.8 },
  },
  {
    id: "mauler",
    name: "Mauler",
    matchNames: ["Mauler"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["engage_and_hold"],
    scoreHints: { closeAndStrike: 2.0 },
  },
  {
    id: "duelist",
    name: "Duelist",
    matchNames: ["Duelist", "Aldori Duelist"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["flank_crit_fish", "engage_and_hold"],
    scoreHints: { offGuardStrike: 1.5 },
  },
  {
    id: "assassin",
    name: "Assassin",
    matchNames: ["Assassin"],
    kind: "other",
    dedicationLevel: 2,
    grantCapabilities: ["sneak_attack"],
    preferPacketIds: ["flank_sneak"],
    scoreHints: { flankSetup: 2.5, offGuardStrike: 2.0 },
  },
  {
    id: "marshal",
    name: "Marshal",
    matchNames: ["Marshal"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["engage_and_hold", "buff_then_blast"],
    scoreHints: { mathBuffFirst: 1.5, guardianPlant: 1.0 },
  },
  {
    id: "medic",
    name: "Medic",
    matchNames: ["Medic"],
    kind: "other",
    dedicationLevel: 2,
    grantCapabilities: ["heal_font"],
    preferPacketIds: ["focus_fire_wounded"],
    scoreHints: { triage: 2.5 },
    roleHint: "cleric",
  },
  {
    id: "sentinel",
    name: "Sentinel",
    matchNames: ["Sentinel"],
    kind: "other",
    dedicationLevel: 2,
    grantCapabilities: ["shield_block"],
    preferPacketIds: ["engage_and_hold"],
    scoreHints: { shieldLayer: 1.5, guardianPlant: 1.2 },
  },
  {
    id: "bastion",
    name: "Bastion",
    matchNames: ["Bastion"],
    kind: "other",
    dedicationLevel: 2,
    grantCapabilities: ["shield_block"],
    preferPacketIds: ["engage_and_hold"],
    scoreHints: { shieldLayer: 2.0 },
  },
  {
    id: "acrobat",
    name: "Acrobat",
    matchNames: ["Acrobat"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["skirmish_exit"],
    scoreHints: { actionCompression: 1.0 },
  },
  {
    id: "poisoner",
    name: "Poisoner",
    matchNames: ["Poisoner"],
    kind: "other",
    dedicationLevel: 2,
    scoreHints: { afflictionSetup: 1.5 },
  },
  {
    id: "snarecrafter",
    name: "Snarecrafter",
    matchNames: ["Snarecrafter", "Trapsmith"],
    kind: "other",
    dedicationLevel: 2,
    scoreHints: { hazardSetup: 1.5 },
  },
  {
    id: "undead",
    name: "Ghoul",
    matchNames: ["Ghoul", "Zombie", "Vampire", "Ghost", "Mummy", "Lich"],
    kind: "other",
    dedicationLevel: 2,
    overlayId: "undead",
    scoreHints: { ignoreFear: 0.5 },
    allowMissingAon: false,
  },
  {
    id: "cavalier",
    name: "Cavalier",
    matchNames: ["Cavalier"],
    kind: "other",
    dedicationLevel: 2,
    preferPacketIds: ["sudden_charge_crash", "engage_and_hold"],
    scoreHints: { closeAndStrike: 1.8 },
  },
  {
    id: "beastmaster",
    name: "Beastmaster",
    matchNames: ["Beastmaster"],
    kind: "other",
    dedicationLevel: 2,
    scoreHints: { companionAssist: 1.0 },
  },
];
