import type { z } from "zod";
import { HazardSchema } from "../../memory/schemas.js";

type HazardInput = z.input<typeof HazardSchema>;

export type CombatHazardStub = HazardInput & {
  matchNames: string[];
  allowMissingAon?: boolean;
};

/** First combat-ready hazard stubs from the general AoN list. */
export const COMBAT_HAZARD_STUBS: CombatHazardStub[] = [
  {
    id: "hidden_pit",
    name: "Hidden Pit",
    matchNames: ["Hidden Pit"],
    level: 0,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 18,
    disableDc: 12,
    disableSkill: "Thievery",
    trigger: "enter_square",
    saveDc: 18,
    halfOnSave: false,
    damageDice: 2,
    damageDie: 6,
    damageBonus: 0,
    applyCondition: "prone",
    once: false,
    paintTags: ["hazardous"],
    summary: "10-ft square pit, 20 ft deep — fall damage on enter.",
  },
  {
    id: "spear_launcher",
    name: "Spear Launcher",
    matchNames: ["Spear Launcher"],
    level: 2,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 20,
    disableDc: 18,
    disableSkill: "Thievery",
    trigger: "enter_square",
    attackBonus: 14,
    damageDice: 2,
    damageDie: 8,
    once: true,
    summary: "Spear shoots from the wall; attack vs AC.",
  },
  {
    id: "fireball_rune",
    name: "Fireball Rune",
    matchNames: ["Fireball Rune"],
    level: 5,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 24,
    disableDc: 22,
    disableSkill: "Thievery",
    trigger: "enter_square",
    saveDc: 22,
    halfOnSave: true,
    damageDice: 6,
    damageDie: 6,
    once: true,
    summary: "Explosive rune — basic Reflex, fire damage.",
  },
  {
    id: "poisoned_lock",
    name: "Poisoned Lock",
    matchNames: ["Poisoned Lock"],
    level: 1,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 18,
    disableDc: 17,
    disableSkill: "Thievery",
    trigger: "manual",
    saveDc: 17,
    halfOnSave: false,
    damageDice: 0,
    applyAffliction: "black_adder_venom",
    once: true,
    summary: "Needle from lock; Fort vs poison on Interact.",
  },
  {
    id: "slamming_door",
    name: "Slamming Door",
    matchNames: ["Slamming Door"],
    level: 1,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 17,
    disableDc: 15,
    disableSkill: "Thievery",
    trigger: "enter_square",
    attackBonus: 13,
    damageDice: 2,
    damageDie: 6,
    once: true,
    summary: "Door slams shut / into creature.",
  },
  {
    id: "scythe_blades",
    name: "Scythe Blades",
    matchNames: ["Scythe Blades"],
    level: 4,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 23,
    disableDc: 21,
    disableSkill: "Thievery",
    trigger: "enter_square",
    attackBonus: 20,
    damageDice: 2,
    damageDie: 12,
    once: true,
    summary: "Swinging scythe blades.",
  },
  {
    id: "hampering_web",
    name: "Hampering Web",
    matchNames: ["Hampering Web"],
    level: 1,
    complexity: "simple",
    hazardType: "environmental",
    stealthDc: 18,
    trigger: "enter_square",
    saveDc: 17,
    halfOnSave: false,
    damageDice: 0,
    applyCondition: "immobilized",
    once: false,
    paintTags: ["difficult"],
    summary: "Sticky webs impede movement.",
  },
  {
    id: "poisonous_mold",
    name: "Poisonous Mold",
    matchNames: ["Poisonous Mold"],
    level: 2,
    complexity: "simple",
    hazardType: "environmental",
    stealthDc: 18,
    trigger: "enter_square",
    saveDc: 16,
    halfOnSave: true,
    damageDice: 2,
    damageDie: 6,
    once: false,
    paintTags: ["hazardous"],
    summary: "Spore cloud — poison damage.",
  },
  {
    id: "electric_latch_rune",
    name: "Electric Latch Rune",
    matchNames: ["Electric Latch Rune"],
    level: 3,
    complexity: "simple",
    hazardType: "trap",
    stealthDc: 20,
    disableDc: 20,
    disableSkill: "Thievery",
    trigger: "manual",
    saveDc: 20,
    halfOnSave: true,
    damageDice: 3,
    damageDie: 12,
    once: true,
    summary: "Electricity when the latch is touched.",
  },
  {
    id: "snowfall",
    name: "Snowfall",
    matchNames: ["Snowfall"],
    level: 0,
    complexity: "simple",
    hazardType: "environmental",
    stealthDc: 16,
    trigger: "enter_square",
    saveDc: 16,
    halfOnSave: false,
    damageDice: 0,
    applyCondition: "clumsy",
    once: false,
    paintTags: ["difficult"],
    summary: "Deep snow — difficult terrain / clumsy.",
  },
  {
    id: "spectral_reflection",
    name: "Spectral Reflection",
    matchNames: ["Spectral Reflection"],
    level: 5,
    complexity: "simple",
    hazardType: "haunt",
    stealthDc: 24,
    trigger: "enter_square",
    saveDc: 22,
    halfOnSave: true,
    damageDice: 4,
    damageDie: 8,
    once: true,
    summary: "Haunt reflection lashes out.",
  },
  {
    id: "spinning_blade_pillar",
    name: "Spinning Blade Pillar",
    matchNames: ["Spinning Blade Pillar"],
    level: 4,
    complexity: "complex",
    hazardType: "trap",
    stealthDc: 25,
    disableDc: 22,
    disableSkill: "Thievery",
    trigger: "end_turn_in",
    attackBonus: 19,
    damageDice: 2,
    damageDie: 12,
    once: false,
    paintTags: ["hazardous"],
    summary: "Complex trap — blades at end of turn in area.",
  },
];
