import type { Spell } from "../../memory/schemas.js";

/**
 * First combat-ready stub set for the sim's SpellSchema.
 * Matched to AoN index rows by `matchNames` (Remaster names preferred).
 *
 * Caster-facing numbers (attackBonus / saveDc / damageBonus) are L1-ish baselines
 * so stubs are immediately castable; override per creature when attaching.
 */
export type CombatSpellStub = {
  /** Stable sim id (snake_case). */
  id: string;
  /** Primary display name (Remaster when applicable). */
  name: string;
  /** Names used to join the AoN HTML index (case-insensitive). */
  matchNames: string[];
  /** Partial SpellSchema fields; Zod fills defaults at ingest time. */
  spell: Partial<Spell> & Pick<Spell, "kind" | "rank">;
};

/** Typical trained L1 caster baselines used by classic fixtures. */
const L1_ATTACK = 7;
const L1_DC = 17;
const L1_MOD = 4;

export const COMBAT_SPELL_STUBS: CombatSpellStub[] = [
  // ── Cantrips ──────────────────────────────────────────────
  {
    id: "ignition",
    name: "Ignition",
    matchNames: ["Ignition", "Produce Flame"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "electric_arc",
    name: "Electric Arc",
    matchNames: ["Electric Arc"],
    spell: {
      kind: "save",
      rank: 0,
      actions: 2,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "divine_lance",
    name: "Divine Lance",
    matchNames: ["Divine Lance"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "frostbite",
    name: "Frostbite",
    matchNames: ["Frostbite", "Ray of Frost"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 12,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "telekinetic_projectile",
    name: "Telekinetic Projectile",
    matchNames: ["Telekinetic Projectile"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 1,
      damageDie: 6,
      damageBonus: L1_MOD,
      rangeCells: 6,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "gouging_claw",
    name: "Gouging Claw",
    matchNames: ["Gouging Claw"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 1,
      damageDie: 6,
      damageBonus: L1_MOD,
      rangeCells: 1,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "needle_darts",
    name: "Needle Darts",
    matchNames: ["Needle Darts"],
    spell: {
      kind: "attack",
      rank: 0,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 3,
      damageDie: 4,
      damageBonus: 0,
      rangeCells: 6,
      halfOnSave: true,
      tactic: "offense",
    },
  },
  {
    id: "caustic_blast",
    name: "Caustic Blast",
    matchNames: ["Caustic Blast", "Acid Splash"],
    spell: {
      kind: "save",
      rank: 0,
      actions: 2,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: true,
      blastRadius: 1,
      tactic: "offense",
    },
  },
  {
    id: "scatter_scree",
    name: "Scatter Scree",
    matchNames: ["Scatter Scree"],
    spell: {
      kind: "save",
      rank: 0,
      actions: 2,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: true,
      areaSquareCells: 2,
      leaveTerrain: "difficult",
      terrainDurationRounds: 10,
      tactic: "control",
    },
  },
  {
    id: "spout",
    name: "Spout",
    matchNames: ["Spout"],
    spell: {
      kind: "save",
      rank: 0,
      actions: 2,
      damageDice: 1,
      damageDie: 4,
      damageBonus: L1_MOD,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: true,
      tactic: "offense",
    },
  },

  // ── Ranked (1–5) ──────────────────────────────────────────
  {
    id: "grease",
    name: "Grease",
    matchNames: ["Grease"],
    spell: {
      kind: "save",
      rank: 1,
      actions: 2,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: false,
      usesPerCombat: 2,
      tactic: "control",
      applyCondition: "off-guard",
      areaSquareCells: 2,
      leaveTerrain: "grease",
      terrainGlyph: "G",
      terrainDurationRounds: 10,
    },
  },
  {
    id: "fog_cloud",
    name: "Fog Cloud",
    matchNames: ["Fog Cloud"],
    spell: {
      kind: "save",
      rank: 1,
      actions: 3,
      rangeCells: 24,
      usesPerCombat: 2,
      tactic: "control",
      // 20-ft burst ≈ Chebyshev r=2 on a 5-ft grid (compact sim footprint).
      blastRadius: 2,
      leaveTerrain: "fog",
      terrainGlyph: "F",
      terrainDurationRounds: 10,
    },
  },
  {
    id: "sleep",
    name: "Sleep",
    matchNames: ["Sleep"],
    spell: {
      kind: "save",
      rank: 1,
      actions: 2,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: false,
      usesPerCombat: 1,
      tactic: "crowd_control",
      applyCondition: "asleep",
      skipIfSaveBonusGte: 5,
      blastRadius: 1,
    },
  },
  {
    id: "heal",
    name: "Heal",
    matchNames: ["Heal"],
    spell: {
      kind: "heal",
      rank: 1,
      actions: 2,
      healDice: 1,
      healDie: 8,
      healBonus: 8,
      rangeCells: 6,
      halfOnSave: true,
      usesPerCombat: 3,
      tactic: "heal",
    },
  },
  {
    id: "fear",
    name: "Fear",
    matchNames: ["Fear"],
    spell: {
      kind: "save",
      rank: 1,
      actions: 2,
      rangeCells: 6,
      saveDc: L1_DC,
      halfOnSave: false,
      usesPerCombat: 2,
      tactic: "crowd_control",
      applyCondition: "frightened",
    },
  },
  {
    id: "hydraulic_push",
    name: "Hydraulic Push",
    matchNames: ["Hydraulic Push"],
    spell: {
      kind: "attack",
      rank: 1,
      actions: 2,
      attackBonus: L1_ATTACK,
      damageDice: 2,
      damageDie: 6,
      damageBonus: 0,
      rangeCells: 12,
      halfOnSave: true,
      usesPerCombat: 2,
      tactic: "offense",
    },
  },
  {
    id: "force_barrage",
    name: "Force Barrage",
    matchNames: ["Force Barrage", "Magic Missile"],
    spell: {
      kind: "attack",
      rank: 1,
      actions: 2,
      // Auto-hit force darts — model as high-certainty attack with small dice.
      attackBonus: 30,
      damageDice: 3,
      damageDie: 4,
      damageBonus: 3,
      rangeCells: 24,
      halfOnSave: true,
      usesPerCombat: 2,
      tactic: "offense",
    },
  },
  {
    id: "thunderstrike",
    name: "Thunderstrike",
    matchNames: ["Thunderstrike"],
    spell: {
      kind: "save",
      rank: 1,
      actions: 2,
      damageDice: 1,
      damageDie: 12,
      damageBonus: 0,
      rangeCells: 24,
      saveDc: L1_DC,
      halfOnSave: true,
      usesPerCombat: 2,
      tactic: "offense",
    },
  },
  {
    id: "blazing_bolt",
    name: "Blazing Bolt",
    matchNames: ["Blazing Bolt"],
    spell: {
      kind: "attack",
      rank: 2,
      actions: 2,
      attackBonus: L1_ATTACK + 2,
      damageDice: 2,
      damageDie: 6,
      damageBonus: 0,
      rangeCells: 12,
      halfOnSave: true,
      usesPerCombat: 2,
      tactic: "offense",
    },
  },
  {
    id: "sudden_bolt",
    name: "Sudden Bolt",
    matchNames: ["Sudden Bolt"],
    spell: {
      kind: "save",
      rank: 2,
      actions: 2,
      damageDice: 4,
      damageDie: 12,
      damageBonus: 0,
      rangeCells: 12,
      saveDc: L1_DC + 2,
      halfOnSave: true,
      usesPerCombat: 1,
      tactic: "offense",
    },
  },
  {
    id: "fireball",
    name: "Fireball",
    matchNames: ["Fireball"],
    spell: {
      kind: "save",
      rank: 3,
      actions: 2,
      damageDice: 6,
      damageDie: 6,
      damageBonus: 0,
      rangeCells: 100,
      saveDc: L1_DC + 4,
      halfOnSave: true,
      usesPerCombat: 1,
      blastRadius: 2,
      tactic: "crowd_control",
    },
  },
  {
    id: "lightning_bolt",
    name: "Lightning Bolt",
    matchNames: ["Lightning Bolt"],
    spell: {
      kind: "save",
      rank: 3,
      actions: 2,
      damageDice: 4,
      damageDie: 12,
      damageBonus: 0,
      rangeCells: 24,
      saveDc: L1_DC + 4,
      halfOnSave: true,
      usesPerCombat: 1,
      // Line approximated as a long thin burst for multi-target scoring.
      blastRadius: 1,
      tactic: "crowd_control",
    },
  },
];
