export type FeatFrequency = "at_will" | "once_combat" | "reaction";
export type FeatEffectClass =
  | "strikeMod"
  | "actionCompression"
  | "setup"
  | "reaction"
  | "healBias"
  | "buff"
  | "terrain"
  | "misc";

/** Existing scorer / packet heads only (v1 does not add new executors). */
export type FeatMappedHead = string;

/**
 * Attempt-oriented combat feat / class-feature stubs.
 * Matched to AoN feat index by `matchNames` when present.
 */
export type CombatFeatStub = {
  /** Stable sim / capability id (snake_case); usually matches overlay key. */
  id: string;
  name: string;
  matchNames: string[];
  /** Class features may be absent from Feats.aspx — still catalog them. */
  allowMissingAon?: boolean;
  overlayId?: string;
  preferPacketIds?: string[];
  head?: FeatMappedHead;
  actions: number;
  frequency: FeatFrequency;
  effectClass: FeatEffectClass;
  needsOffGuard?: boolean;
  needsRaisedShield?: boolean;
  needsAdjacentFoe?: boolean;
  needsReactionAvailable?: boolean;
  minActions?: number;
  /** Skip prefer-boost when MAP is already this high. */
  maxMap?: number;
  avoidThirdStrike?: boolean;
  /** Default score hint when attempt is true. */
  scoreHint: number;
};

export const COMBAT_FEAT_STUBS: CombatFeatStub[] = [
  {
    id: "reactive_strike",
    name: "Reactive Strike",
    matchNames: ["Reactive Strike", "Attack of Opportunity"],
    overlayId: "reactive_strike",
    preferPacketIds: ["engage_and_hold", "flank_crit_fish"],
    head: "Raise_Shield",
    actions: 0,
    frequency: "reaction",
    effectClass: "reaction",
    needsAdjacentFoe: true,
    needsReactionAvailable: true,
    avoidThirdStrike: true,
    scoreHint: 1.5,
  },
  {
    id: "sneak_attack",
    name: "Sneak Attack",
    matchNames: ["Sneak Attack", "Precise Strike"],
    allowMissingAon: true,
    overlayId: "sneak_attack",
    preferPacketIds: ["flank_sneak", "skirmish_exit"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsOffGuard: true,
    maxMap: 0,
    scoreHint: 2.5,
  },
  {
    id: "flurry_of_blows",
    name: "Flurry of Blows",
    matchNames: ["Flurry of Blows"],
    allowMissingAon: true,
    overlayId: "flurry_of_blows",
    preferPacketIds: ["flurry_skirmish", "skirmish_exit"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "actionCompression",
    needsAdjacentFoe: true,
    minActions: 1,
    maxMap: 0,
    scoreHint: 1.5,
  },
  {
    id: "shield_block",
    name: "Shield Block",
    matchNames: ["Shield Block"],
    allowMissingAon: true,
    overlayId: "shield_block",
    preferPacketIds: ["engage_and_hold"],
    head: "Raise_Shield",
    actions: 0,
    frequency: "reaction",
    effectClass: "reaction",
    needsRaisedShield: true,
    needsReactionAvailable: true,
    scoreHint: 1.2,
  },
  {
    id: "sudden_charge",
    name: "Sudden Charge",
    matchNames: ["Sudden Charge"],
    overlayId: "sudden_charge",
    preferPacketIds: ["sudden_charge_crash"],
    head: "Stride_close",
    actions: 2,
    frequency: "at_will",
    effectClass: "setup",
    minActions: 2,
    maxMap: 0,
    scoreHint: 2.0,
  },
  {
    id: "inspire_courage",
    name: "Courageous Anthem",
    matchNames: ["Courageous Anthem", "Inspire Courage", "Rallying Anthem"],
    allowMissingAon: true,
    overlayId: "inspire_courage",
    preferPacketIds: ["buff_then_blast"],
    head: "Cast_spell",
    actions: 1,
    frequency: "at_will",
    effectClass: "buff",
    minActions: 1,
    scoreHint: 2.5,
  },
  {
    id: "heal_font",
    name: "Healing Font",
    matchNames: ["Healing Hands", "Holy Castigation"],
    allowMissingAon: true,
    overlayId: "heal_font",
    preferPacketIds: ["focus_fire_wounded"],
    head: "Heal_ally",
    actions: 2,
    frequency: "at_will",
    effectClass: "healBias",
    minActions: 1,
    scoreHint: 2.5,
  },
  {
    id: "cast_focus",
    name: "Focus Spells",
    matchNames: [],
    allowMissingAon: true,
    overlayId: "cast_focus",
    preferPacketIds: [
      "save_arbitrage_blast",
      "control_then_mitigate",
      "buff_then_blast",
    ],
    head: "Cast_spell",
    actions: 2,
    frequency: "once_combat",
    effectClass: "misc",
    minActions: 2,
    scoreHint: 1.5,
  },
  {
    id: "ignore_difficult_terrain",
    name: "Ignore Difficult Terrain",
    matchNames: ["Woodland Stride", "Fleet", "Cloud Jump"],
    allowMissingAon: true,
    overlayId: "ignore_difficult_terrain",
    head: "Stride_close",
    actions: 0,
    frequency: "at_will",
    effectClass: "terrain",
    scoreHint: 1.0,
  },
  {
    id: "champion_dedication",
    name: "Champion Dedication",
    matchNames: ["Champion Dedication"],
    overlayId: "champion_dedication",
    preferPacketIds: ["engage_and_hold"],
    head: "Raise_Shield",
    actions: 0,
    frequency: "reaction",
    effectClass: "reaction",
    needsAdjacentFoe: true,
    scoreHint: 1.0,
  },
  {
    id: "combat_flexibility",
    name: "Combat Flexibility",
    matchNames: ["Combat Flexibility"],
    allowMissingAon: true,
    overlayId: "combat_flexibility",
    actions: 0,
    frequency: "once_combat",
    effectClass: "misc",
    scoreHint: 1.0,
  },
  {
    id: "power_attack",
    name: "Power Attack",
    matchNames: ["Power Attack"],
    preferPacketIds: ["engage_and_hold", "flank_crit_fish"],
    head: "Strike_melee",
    actions: 2,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsAdjacentFoe: true,
    minActions: 2,
    maxMap: 0,
    scoreHint: 1.8,
  },
  {
    id: "exacting_strike",
    name: "Exacting Strike",
    matchNames: ["Exacting Strike"],
    preferPacketIds: ["engage_and_hold", "flank_crit_fish"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsAdjacentFoe: true,
    maxMap: 1,
    scoreHint: 1.4,
  },
  {
    id: "intimidating_strike",
    name: "Intimidating Strike",
    matchNames: ["Intimidating Strike"],
    preferPacketIds: ["engage_and_hold"],
    head: "Strike_melee",
    actions: 2,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsAdjacentFoe: true,
    minActions: 2,
    maxMap: 0,
    scoreHint: 1.6,
  },
  {
    id: "vicious_swing",
    name: "Vicious Swing",
    matchNames: ["Vicious Swing", "Power Attack"],
    preferPacketIds: ["engage_and_hold"],
    head: "Strike_melee",
    actions: 2,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsAdjacentFoe: true,
    minActions: 2,
    maxMap: 0,
    scoreHint: 1.8,
  },
  {
    id: "combat_grab",
    name: "Combat Grab",
    matchNames: ["Combat Grab"],
    preferPacketIds: ["engage_and_hold"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "strikeMod",
    needsAdjacentFoe: true,
    maxMap: 0,
    scoreHint: 1.3,
  },
  {
    id: "knockdown",
    name: "Knockdown",
    matchNames: ["Knockdown"],
    preferPacketIds: ["engage_and_hold"],
    head: "Strike_melee",
    actions: 2,
    frequency: "at_will",
    effectClass: "setup",
    needsAdjacentFoe: true,
    minActions: 2,
    maxMap: 0,
    scoreHint: 1.7,
  },
  {
    id: "twin_feint",
    name: "Twin Feint",
    matchNames: ["Twin Feint"],
    preferPacketIds: ["flank_sneak", "skirmish_exit"],
    head: "Strike_melee",
    actions: 2,
    frequency: "at_will",
    effectClass: "setup",
    needsAdjacentFoe: true,
    minActions: 2,
    maxMap: 0,
    scoreHint: 2.0,
  },
  {
    id: "dread_striker",
    name: "Dread Striker",
    matchNames: ["Dread Striker"],
    preferPacketIds: ["flank_sneak"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "strikeMod",
    scoreHint: 1.2,
  },
  {
    id: "brutal_critical",
    name: "Brutal Critical",
    matchNames: ["Brutal Critical", "Critical Debilitation"],
    preferPacketIds: ["flank_crit_fish", "engage_and_hold"],
    head: "Strike_melee",
    actions: 1,
    frequency: "at_will",
    effectClass: "strikeMod",
    scoreHint: 0.8,
  },
  {
    id: "point_blank_shot",
    name: "Point-Blank Shot",
    matchNames: ["Point-Blank Shot"],
    head: "Strike_ranged",
    actions: 1,
    frequency: "at_will",
    effectClass: "setup",
    minActions: 1,
    scoreHint: 1.1,
  },
  {
    id: "running_reload",
    name: "Running Reload",
    matchNames: ["Running Reload"],
    head: "Stride_close",
    actions: 1,
    frequency: "at_will",
    effectClass: "actionCompression",
    scoreHint: 1.0,
  },
  {
    id: "kip_up",
    name: "Kip Up",
    matchNames: ["Kip Up"],
    head: "Step_away",
    actions: 0,
    frequency: "at_will",
    effectClass: "setup",
    scoreHint: 0.5,
  },
  {
    id: "nimble_dodge",
    name: "Nimble Dodge",
    matchNames: ["Nimble Dodge"],
    head: "Step_away",
    actions: 0,
    frequency: "reaction",
    effectClass: "reaction",
    needsReactionAvailable: true,
    scoreHint: 1.0,
  },
  {
    id: "opportune_backstab",
    name: "Opportune Backstab",
    matchNames: ["Opportune Backstab"],
    preferPacketIds: ["flank_sneak"],
    head: "Strike_melee",
    actions: 0,
    frequency: "reaction",
    effectClass: "reaction",
    needsOffGuard: true,
    needsReactionAvailable: true,
    scoreHint: 1.8,
  },
];
